myTheme <- theme(text = element_text(colour = "#2E4053"),
                 plot.title = element_text(face = "bold", size = 12, colour = "#2E4053"),
                 plot.subtitle = element_text(face = "bold", size = 10, colour = "#2E4053"),
                 axis.text.y = element_text(colour = "#2B3947", size = 10),
                 axis.text.x = element_text(colour = "#2B3947", size = 10),
                 axis.title.y = element_text(colour = "#2B3947", size = 11),
                 axis.title.x = element_text(colour = "#2B3947", size = 11),
                 axis.ticks.y = element_blank(),
                 axis.ticks.x = element_blank(),
                 strip.text = element_text(face = "bold", size = 9.5, colour = "#2B3947" ),
                 strip.background = element_blank(),
                 panel.background = element_rect(fill = "white", colour = "transparent", size = 2),
                 panel.grid.major.x = element_line(colour = "#aeb6bf"),
                 panel.grid.major.y = element_line(colour = "#aeb6bf"),
                 panel.spacing = unit(0.5, "cm"),
                 legend.position = "bottom",
                 panel.border = element_rect(fill = "transparent", colour = "white", size = 5))
